### PR TITLE
Fix thrust builds in 1.1.0

### PR DESCRIPTION
**Pull request by cferenba**
Fix thrust builds in the 1.1.0 release, by adding some explicit std:: namespaces where needed.

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by cferenba** [comment]
@nray discovered that flecsale does not build against portage master.  I've just added a commit to fix that.

**Review by cmsquared — APPROVED** [review]
We these changes and @nray 's PR we should either move the 1.1.0 tag, or do a bugfix release at 1.1.1.  There are also a couple of docs fixes that need to go in as well.  I'll leave the tag vs bugfix decision to @angelaherring

**Comment by junghans** [comment]
See https://www.kernel.org/pub/software/scm/git/docs/git-tag.html on Re-tagging

**Comment by cferenba** [comment]
I think enough time has passed that we should tag these as a 1.1.1 bugfix release.
For next time, we should probably do a release candidate that we spend a few days testing before doing the real release.

**Pull request closed without merging**
