### PR TITLE
cmake: add libmpi where needed

### LINKED ISSUE #8: No need to set CMAKE_C_COMPILER to mpicc
There is basically no need for `CMAKE_C_COMPILER=$(which mpicc)` (as suggested in the documentation) when CMake is calling `find_package(MPI)` (as we do).

Travis already builds portage this way with MPI. Plus, setting `CMAKE_C_COMPILER` might even lead to some strange build errors if the `mpicc` in your `PATH` differs from what CMake picks up with `find_package(MPI)`.

### PR DESCRIPTION
**Pull request by junghans**
Fix #8 

Sorry, I don't do internal! And on a second thought, it would be nicer to add `${MPI_CXX_LIBRARIES}` to `${EXTRA_LIBS}`.

### CODE REVIEW

**Comment by junghans** [comment]
And I am still confused why travis works at all....

**Comment by junghans** [comment]
Got it, there are multiple `env:` section in `.travis.yml` (https://lint.travis-ci.org/laristra/portage), so the lastest one is used and hence `MPI` is off.

This is also related to #7.

**Comment by junghans** [comment]
We are back in business.

**Comment by cmsquared** [comment]
Sorry I didn't see this earlier. I basically have the same fix internally as a PR there.  It also includes changes to the docs.  I can mirror your travis changes there too.

Should we just close this?  I hate that you have already done work on it though...

**Comment by junghans** [comment]
Do whatever is easiest for you! The changes aren't here substantial!

**Comment by cmsquared** [comment]
I will go ahead and close this then as it is easier to push out to GH than to pull in from GH with our current workflow.

I'll mirror the necessary changes  you have here to our internal PR and get that merged.  The changes will be in 1.1.2, which should be out in a couple of weeks.

**Pull request closed without merging**
