### PR TITLE
Release 2.2.3

### PR DESCRIPTION
**Pull request by hobywan**
There were too many conflicts and I used [another](https://stackoverflow.com/questions/173919/is-there-a-theirs-version-of-git-merge-s-ours/18682314#18682314) method to resolve them.
Hence the commits were not squashed, sorry.
EDIT: I can squash them prior to merge.

### CODE REVIEW

**Comment by hobywan** [comment]
It needs the version 1.1.4 of Wonton to pass.

**Comment by raovgarimella** [comment]
Hoby
I think your method is the right thing to do. I have been saying for a while that we have to effectivelly overwrite the source on the github repo with the one from the xcp-stash using "checkout --ours/theirs". It looks like that's what you have done.

I would recommend adding this info to the confluence page on github releasing workflow.
Rao

**Comment by hobywan** [comment]
> I would recommend adding this info to the confluence page on github releasing workflow.

Okay. I will.

**Comment by hobywan** [comment]
I updated the Wonton hash and Travis tests should normally pass.
Please review at your earliest convenience so that it can be merged as soon as they are completed.

**Review by nray — APPROVED** [review]

**Pull request merged**
